POST http://localhost:8080/api/abc
Content-Type: application/json

{
  "name": "Susi",
  "b": [
    {
      "text": "abc"
    },
    {
      "text": "def",
      "c": [
        {
          "id": 1
        }
      ]
    }
  ]
}