GET http://localhost:8080/hello

### Zeitserver

GET http://localhost:8080/time

###

GET http://localhost:8080/customer/id/susi

###

GET http://localhost:8080/customer/id/hansi

###

GET http://localhost:8080/customer?fn=Dagobert&ln=Duck

###

POST http://localhost:8080/customer
Content-Type: application/x-www-form-urlencoded

name=Dagobert&dob=2021-10-18

###

POST http://localhost:8080/customer/name
Content-Type: application/json

{
  "name":"Dagobert",
  "dob":"2021-10-18"
}

###

GET http://localhost:8080/api/person

###

#http://localhost:8080/api/person
#
#HTTP/1.1 200 OK
#Content-Type: application/json
#content-length: 166
#
#[
#  {
#    "id": 1,
#    "name": "Susi"
#  },
#  {
#    "id": 2,
#    "name": "Seppi"
#  },
#  {
#    "id": 3,
#    "name": "Mimi"
#  },
#  {
#    "id": 4,
#    "name": "Hautzi"
#  },
#  {
#    "id": 5,
#    "name": "Sami"
#  },
#  {
#    "id": 6,
#    "name": "Kiki"
#  },
#  {
#    "id": 7,
#    "name": "Hansi"
#  }
#]
#Response file saved.
#> 2021-11-30T094429.200.json
#
#Response code: 200 (OK); Time: 38ms; Content length: 166 bytes


###